http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]
#Para no tener problemas en el proxy
xpack.fleet.registryProxyUrl: your-nat-gateway.corp.net
